import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar';
import TopContent from '../components/TopContent';
import AboutUs from '../components/AboutUs';
import Projects from '../components/Projects';
import Contact from '../components/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Odessa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-100 bg-stone-900'>
        <Navbar />
        <TopContent />
        <AboutUs />
        <Projects />
        <Contact />
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
